import React, { Component } from 'react';
import Heading from './../components/Heading.js';
import Text from './../components/Text.js';
import Box from './../components/Box.js';
import Input from './../components/Input.js';
import Slider from './../components/Slider.js';
import Flexbox from './../components/Flexbox.js';

class Dimensions extends Component {
  render() {
    return (
      <Box
        p3>
        <Box
          table>
          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                size1
                gray600
                right>
                Size
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                W
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Input
                defaultValue="0"/>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                H
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle>
              <Input
                defaultValue="0"/>
            </Box>
          </Box>
          <Box
            pb2>
          </Box>
          <Box
            tablerow
            mb2>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                size1
                gray600
                right>
                Min
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                W
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Input
                defaultValue="0"/>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                H
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle>
              <Input
                defaultValue="0"/>
            </Box>
          </Box>
          <Box
            pb2>
          </Box>
          <Box
            tablerow
            mb2>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                size1
                gray600
                right>
                Max
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                W
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Input
                defaultValue="0"/>
            </Box>
            <Box
              tablecell
              alignmiddle
              pr2>
              <Text
                size1
                gray600
                right>
                H
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle>
              <Input
                defaultValue="0"/>
            </Box>
          </Box>
        </Box>
      </Box>
    );
  }
}

export default Dimensions;
