import React, { Component } from 'react';
import Heading from './../components/Heading.js';
import Text from './../components/Text.js';
import Box from './../components/Box.js';
import Input from './../components/Input.js';
import Slider from './../components/Slider.js';
import Flexbox from './../components/Flexbox.js';

class Transforms extends Component {
  render() {
    return (
      <Box
        p3
        bt
        bcgray300>
        <Box
          table>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Rotate
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                X
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Y
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Z
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Scale
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                X
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Y
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Z
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Translate
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                X
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Y
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Z
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Skew
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                X
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

          <Box
            pb1>
          </Box>

          <Box
            tablerow>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Text
                gray600
                size1
                right>
                Y
              </Text>
            </Box>
            <Box
              tablecell
              alignmiddle
              right
              pr2>
              <Slider
                type="range"
                defaultValue="0" />
            </Box>
            <Box
              tablecell
              alignmiddle
              right>
              <Input
                defaultValue="0"
                size="8"/>
            </Box>
          </Box>

        </Box>

      </Box>
    );
  }
}

export default Transforms;
